import 'package:hive/hive.dart';
import 'package:uuid/uuid.dart';

part 'playlist_model.g.dart'; // This will be generated by hive_generator

@HiveType(typeId: 0)
class AppPlaylist {
  @HiveField(0)
  final String id;
  
  @HiveField(1)
  String name;
  
  @HiveField(2)
  final DateTime createdDate;
  
  @HiveField(3)
  final List<String> songIds; // Store MediaItem URIs
  
  @HiveField(4)
  String? description;
  
  @HiveField(5)
  String? coverImagePath;
  
  AppPlaylist({
    String? id,
    required this.name,
    List<String>? songIds,
    this.description,
    this.coverImagePath,
  })  : id = id ?? const Uuid().v4(),
        createdDate = DateTime.now(),
        songIds = songIds ?? [];
  
  int get songCount => songIds.length;
  
  void addSong(String songId) {
    if (!songIds.contains(songId)) {
      songIds.add(songId);
    }
  }
  
  void removeSong(String songId) {
    songIds.remove(songId);
  }
  
  void updateName(String newName) {
    name = newName;
  }
  
  void clearSongs() {
    songIds.clear();
  }
  
  bool containsSong(String songId) => songIds.contains(songId);
  
  // Helper method to reorder songs
  void reorderSongs(int oldIndex, int newIndex) {
    if (oldIndex < newIndex) {
      newIndex -= 1;
    }
    final songId = songIds.removeAt(oldIndex);
    songIds.insert(newIndex, songId);
  }
  
  Map<String, dynamic> toJson() => {
    'id': id,
    'name': name,
    'songCount': songCount,
    'createdDate': createdDate.toIso8601String(),
    'description': description,
  };
}